### ISSUE TITLE
RuntimeError: While copying the parameter named word_lut.weight

### ISSUE THREAD

**Issue by luofuli** [shrimai/Style-Transfer-Through-Back-Translation#10]
If you face RuntimeError as follows when runing the fourth command in `style_decoder/example.sh`  ( like `python translate.py -encoder_model ../models/translation/french_english/french_english.pt -decoder_model ../models/style_generators/democratic_generator.pt -src ../data/political_data/republican_only.test.fr -output trained_models/republican_democratic.txt -replace_unk $true
`), 

you may need to update the [Translator_style.py](https://github.com/luofuli/Style-Transfer-Through-Back-Translation/commit/25136c0b7e1cd7aaa19901d12924bb94d1151bcc)
```
Traceback (most recent call last):
File "translate.py", line 140, in <module> main() File "translate.py", line 66, in main translator = onmt.Translator_style(opt) File "/home/tyt/style-trans/Style-Transfer-Through-Back-Translation-master/style_decoder/onmt/Translator_style.py", line 22, in __init__ decoder.load_state_dict(checkpoint['decoder'])
File "/home/tyt/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named word_lut.weight, whose dimensions in the model are torch.Size([9603, 300]) and whose dimensions in the checkpoint are torch.Size([9603, 100]).
```
Am I right?

**Comment by shrimai** [comment]
Yes, you have make sure that the dimensions of the model you are loading matches the graph you are making. You have to make changes in the Translator_style.py file.
