### ISSUE TITLE
Error training a new classifier 

### ISSUE THREAD

**Issue by ninikolov** [shrimai/Style-Transfer-Through-Back-Translation#11]
Hi, I'm trying to train a new CNN classifier, but getting the following exception: 

Namespace(batch_size=40, curriculum=False, data='data.pt', dropout=0.2, epochs=13, extra_shuffle=False, filter_size=5, gpus=[3], learning_rate=1.0, learning_rate_decay=0.5, log_interval=50, max_generator_batches=32, max_grad_norm=5, num_classes=2, num_filters=100, optim='sgd', param_init=0.1, pre_word_vecs_enc=None, save_model='cnn', sequence_length=50, start_decay_at=8, start_epoch=1, train_from='', train_from_state_dict='', word_vec_size=300)
Loading data from 'wiki-simple-cnn.train.pt'
 * vocabulary size. source = 50004;
 * number of training sentences. 1889378
 * maximum batch size. 40
Building model...
* number of parameters: 15151401

/home/nikola/anaconda3/envs/env/lib/python3.5/site-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([40])) that is different to the input size (torch.Size([400])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "/home/nikola/PhD/code/back-translation-copy/classifier/cnn_train.py", line 342, in <module>
    main()
  File "/home/nikola/PhD/code/back-translation-copy/classifier/cnn_train.py", line 339, in main
    trainModel(model, trainData, validData, dataset, optim)
  File "/home/nikola/PhD/code/back-translation-copy/classifier/cnn_train.py", line 240, in trainModel
    train_loss, train_acc = trainEpoch(epoch)
  File "/home/nikola/PhD/code/back-translation-copy/classifier/cnn_train.py", line 210, in trainEpoch
    outputs, targets, model, criterion)
  File "/home/nikola/PhD/code/back-translation-copy/classifier/cnn_train.py", line 125, in memoryEfficientLoss
    loss_t = crit(outputs.squeeze(-1), targets[0].float())
  File "/home/nikola/anaconda3/envs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nikola/anaconda3/envs/env/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 372, in forward
    size_average=self.size_average)
  File "/home/nikola/anaconda3/envs/env/lib/python3.5/site-packages/torch/nn/functional.py", line 1171, in binary_cross_entropy
    "!= input nelement ({})".format(target.nelement(), input.nelement()))
ValueError: Target and input must have the same number of elements. target nelement (40) != input nelement (400)

Using python 3.5 and PyTorch 0.3.0. Any tips would be appreciated. Thanks

**Comment by ninikolov** [comment]
I figured out where the problem is coming from - fails when trying to train on sequences larger than 50 tokens. If I set to 50 when preprocessing the data, the CNN trains.

**Comment by shrimai** [comment]
Great. If you want to train on sequences larger than 50, you can set the parameter "sequence_length" accordingly.

**Comment by ninikolov** [comment]
thanks

**Comment by chejmadi** [comment]
How do you train it exactly? The cnn_train.py code requires a -data argument, which example.sh says should be political.train.pt. Where is that .pt file coming from?

**Comment by shrimai** [comment]
Please use the instructions on the home page of this git repo to download all the required data files.
