### ISSUE TITLE
Translation RuntimeError

### ISSUE THREAD

**Issue by Jaxonwht** [shrimai/Style-Transfer-Through-Back-Translation#13]
When I was running translation.py with the given model and data, a RuntimeError occurred because number of sizes is smaller than number of dimensions in the tensor.
```
[haotian@jaxon style_decoder]$ python translate.py -model ../models/translation/english_french/english_french.pt -src ../data/political_data/democratic_only.train.en -output ../data/political_data/democratic_only.train.fr -replace_unk $true
/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Dataset.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b = Variable(b, volatile=self.volatile)
/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator.py:126: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  Variable(input, volatile=True), decStates, context, decOut)
Traceback (most recent call last):
  File "translate.py", line 139, in <module>
    main()
  File "translate.py", line 93, in main
    predBatch, predScore, goldScore = translator.translate(srcBatch, tgtBatch)
  File "/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator.py", line 197, in translate
    pred, predScore, attn, goldScore = self.translateBatch(src, tgt)
  File "/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator.py", line 126, in translateBatch
    Variable(input, volatile=True), decStates, context, decOut)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Models.py", line 108, in forward
    output, attn = self.attn(output, context.transpose(0, 1))
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haotian/Desktop/Polarization Lab/Style-Transfer-Through-Back-Translation/style_decoder/onmt/modules/GlobalAttention.py", line 49, in forward
    attn.data.masked_fill_(self.mask, -float('inf'))
RuntimeError: expand(torch.ByteTensor{[5, 30, 43]}, size=[150, 43]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
```

**Comment by shrimai** [comment]
I think it is some pytorch version error:
https://github.com/salesforce/decaNLP/issues/14
https://github.com/pytorch/pytorch/issues/4228
Please check the version.

**Comment by Jaxonwht** [comment]
The issue was solved by installing pyTorch0.3.0 with Python 3.6.6, cuda8.0
