### ISSUE TITLE
RuntimeError while running translate.py in style_decoder 

### ISSUE THREAD

**Issue by chejmadi** [shrimai/Style-Transfer-Through-Back-Translation#19]
While running the English-French translation, we get a RuntimeError:

`C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\Dataset.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b = Variable(b, volatile=self.volatile)
C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\Translator.py:126: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  Variable(input, volatile=True), decStates, context, decOut)
Traceback (most recent call last):
  File "translate.py", line 139, in <module>
    main()
  File "translate.py", line 93, in main
    predBatch, predScore, goldScore = translator.translate(srcBatch, tgtBatch)
  File "C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\Translator.py", line 197, in translate
    pred, predScore, attn, goldScore = self.translateBatch(src, tgt)
  File "C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\Translator.py", line 126, in translateBatch
    Variable(input, volatile=True), decStates, context, decOut)
  File "C:\Users\chinm\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\Models.py", line 108, in forward
    output, attn = self.attn(output, context.transpose(0, 1))
  File "C:\Users\chinm\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\chinm\Downloads\DLProj\Style-Transfer-Through-Back-Translation\style_decoder\onmt\modules\GlobalAttention.py", line 49, in forward
    attn.data.masked_fill_(self.mask, -float('inf'))
RuntimeError: expand(torch.ByteTensor{[5, 30, 43]}, size=[150, 43]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)`

What could be the cause of this error? We haven't tinkered with the code at all, other than using the Translator.py file instead of Translator_style and other stuff that was advised. We are running this on a CPU as of now though, if that matters. 

We suspect this has something to do with the fact that "volatile" has been removed, as the warning says, i.e., we are using PyTorch 1.0.1 instead of PyTorch 0.3.0. Do you know of any workaround to this?

**Comment by shrimai** [comment]
Yes, this code is to be run on PyTorch 0.3.0 or 0.3.1. It will not run with higher versions of PyTorch. Please refer to the [migration guide](https://pytorch.org/blog/pytorch-0_4_0-migration-guide/) for converting this code base to Pytorch 1.0
