### ISSUE TITLE
Not able to translate(no style transfer, only translation) 

### ISSUE THREAD

**Issue by SOURO** [shrimai/Style-Transfer-Through-Back-Translation#24]
I am following your example.sh
I want to generate republican_only.test.fr from the republican_only.test.en 

so if I am running the below command,
`python translate.py -model ../models/translation/english_french/english_french.pt -src ../data/political_data/democratic_only.train.en -output ../data/political_data/democratic_only.train.fr -replace_unk $true`

I am getting the below error,
`translate.py: error: the following arguments are required: -encoder_model, -decoder_model`

so i guess -encoder_model will be (-model ../models/translation/english_french/english_french.pt) but what will be the -decoder_model ? I cant use the style generator model here right? because I just simply want to I want to generate republican_only.test.fr from the republican_only.test.en at first without style transfer. Please help.

**Comment by SOURO** [comment]
What I tried again is ,
`python translate.py -encoder_model ../models/translation/english_french/english_french.pt -decoder_model ../models/translation/english_french/english_french.pt -src ../data/political_data/democratic_only.train.en -output ../data/political_data/democratic_only.train.fr -replace_unk $true`

used the same -model as -encoder_model and -decoder_model and then got the below error,
`Traceback (most recent call last):
  File "translate.py", line 139, in <module>
    main()
  File "translate.py", line 66, in main
    translator = onmt.Translator_style(opt)
  File "/lnet/work/people/mukherjee/own_code/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator_style.py", line 20, in __init__
    encoder.load_state_dict(encoder_check['encoder'])
KeyError: 'encoder'
`

what needs to be done? Please help.

**Comment by SOURO** [comment]
I am using python and pytorch version same as mentioned by you.

**Comment by SOURO** [comment]
I found the solution ... I have seen in the code that commenting and commenting of specific part required ... My bad ...Sorry for disturbing ...

**Comment by SOURO** [comment]
`## When using english-french trained MT model, uncomment -model
## and comment -encoder_model and -decoder_model
parser.add_argument('-model', required=True,
                    help='Path to model .pt file')
#parser.add_argument('-encoder_model', required=True,
#                    help='Path to model .pt file')
#parser.add_argument('-decoder_model', required=True,
#                    help='Path to model .pt file')`

I did this, but then again getting the below error,

`Traceback (most recent call last):
  File "translate.py", line 139, in <module>
    main()
  File "translate.py", line 66, in main
    translator = onmt.Translator_style(opt)
  File "/lnet/work/people/mukherjee/own_code/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator_style.py", line 12, in __init__
    checkpoint = torch.load(opt.decoder_model, map_location=lambda storage, loc: storage)
AttributeError: 'Namespace' object has no attribute 'decoder_model'`
