### ISSUE TITLE
Missing `political_classifier_vocab.src.dict`

### ISSUE THREAD

**Issue by johntiger1** [shrimai/Style-Transfer-Through-Back-Translation#6]
Would it be possible to provide this in the `http://tts.speech.cs.cmu.edu/style_models/political_data.tar` file? 

When I run this line:
https://github.com/shrimai/Style-Transfer-Through-Back-Translation/blob/ce44ea946eef5df4c725ccf0319392d105408495/style_decoder/example.sh#L14

I get 

```
(backstyle) johnchen@vws53:~/Desktop/git_stuff/Style-Transfer-Through-Back-Translation/style_decoder$ python preprocess.py -train_src ../data/political_data/democratic_only.train.fr -train_tgt ../data/political_data/democratic_only.train.en -valid_src ../data/political_data/democratic_only.dev.fr -valid_tgt ../data/political_data/democratic_only.dev.en -save_data data/democratic_generator -src_vocab ../models/translation/french_english/french_english_vocab.src.dict -tgt_vocab ../models/classifier/political_classifier/political_classifier_vocab.src.dict -seq_len 50
Preparing source vocab ....
Reading source vocabulary from '../models/translation/french_english/french_english_vocab.src.dict'...
Loaded 100004 source words

Preparing target vocab ....
Reading target vocabulary from '../models/classifier/political_classifier/political_classifier_vocab.src.dict'...
Traceback (most recent call last):
  File "preprocess.py", line 238, in <module>
    main()
  File "preprocess.py", line 178, in main
    opt.tgt_vocab_size)
  File "preprocess.py", line 76, in initVocabulary
    vocab.loadFile(vocabFile)
  File "/h/johnchen/Desktop/git_stuff/Style-Transfer-Through-Back-Translation/style_decoder/onmt/Dict.py", line 25, in loadFile
    for line in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '../models/classifier/political_classifier/political_classifier_vocab.src.dict'
```

From my understanding, you can also generate this source voacb dict from training the classifier; however, in that case could we get the dev.txt file provided? 

Thanks!

**Comment by shrimai** [comment]
If you untar the political_classifier.tar file, the political_classifier_vocab.src.dict file should be there in the folder.

**Comment by johntiger1** [comment]
Thanks! The vocab file was indeed there. I also had to make a `data` folder in the same folder as the `preprocess.py` to get it to work
